defaults:
  - _self_
  - planner: mppi
  - train: off_policy
  - wandb: sweep
  - model: moe
  - agent: sac
  - overrides: half_cheetah
  - buffer: random_replay_buffer

root_dir: "../experiments"
mode: "train_dads"  # others are
device: "cpu"

hydra:
  run:
    dir: ${root_dir}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}