defaults:
  - _self_
  - env: ant
  - planner: mppi
  - train: off_policy
  - wandb: sweep

root_dir: "./exp"
mode: "mppi_test"  # others are

hydra:
  run:
    dir: ${root_dir}/${mode}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ${root_dir}/${mode}/${now:%Y.%m.%d}/${now:%H%M%S}